//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PitcherDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitcher
    {
        public int PitcherID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Fastball { get; set; }
        public Nullable<int> Curve { get; set; }
        public Nullable<int> Slider { get; set; }
        public Nullable<int> ChangeUp { get; set; }
        public Nullable<int> Sinker { get; set; }
        public Nullable<int> Splitter { get; set; }
        public Nullable<int> Cutter { get; set; }
    }
}
